<? $this->headTitle('Work Records'); ?>

<?
$ppm_session = new Zend_Session_Namespace('ppm');
$registry = Zend_Registry::getInstance();
$acl = $registry->acl;
$u = $ppm_session->user;

$this->headLink()->appendStylesheet('/css/paginator.css', 'screen');
?>

<a name="top"></a>
<h1>Work Record</h1>

<p>The list below shows the activities carried out onsite as part of the upkeep of the Mansions.</p>
     
<? if ($acl->isAllowed($u->getRole(), 'workrecord', 'add')): ?>
<button name="addWorkrecord"
   title="Add a new work record" class="btn"
   onclick="javascript:document.location='/workrecord/add'">Add Work Record...</button>
<? endif; ?>

<?php if (count($this->paginator) == 0): ?>
    <div class="alert alert-warn">
    <strong>Note:</strong> No work records found.
    </div>
<?php else: ?>

   <!-- Loop through the entries that were provided to us by the controller -->
   <table class="document">
   <?php $counter = 0; ?>
   <?php foreach ($this->paginator as $entry):?>
      <tr>
         <td>
            <?php echo $this->escape($entry['work_date']) ?>
         </td>
         <td>
            <?php echo nl2br($entry['notes']) ?>
         </td>
         <td>
            <?php echo $this->escape($entry['hours']) ?> hrs
         </td>
         <td>
         <? if ($acl->isAllowed($u->getRole(), 'workrecord', 'delete')): ?>
               <a class="action"
                  name="deleteWorkrecord"
                  title="Delete this work record"
                  href="<?= $this->url(array('controller' => 'workrecord', 'action' => 'delete', 'id' => $entry['id'])) ?>">Delete</a>
         <? endif; ?>
         </td>
      </tr>
         
   <?php endforeach;?>
   </table>
   
   <?php echo $this->paginationControl($this->paginator, 'Sliding',  'paginator.phtml'); ?>
   
<?php endif; ?>

<br />

<br />