<? $this->headTitle('Caretaker'); ?>

<a name="top"></a><h1>Caretaker</h1>

<div class="row">
    <div class="span5">
    <a name="details"></a><h2>Caretaker&#39;s Details</h2>
    
    <p>PPM has a caretaker, Sean Gereson, who works 35 hours per week. He has a
    wealth of experience and is more than capable of performing caretaker tasks and dealing with
    trades-people. His working hours and duties are detailed in the following sections.</p>
    
    <a name="hours"></a><h2>Working Hours</h2>
    
    <p>Sean&#39;s working hours are 9am - 4:30pm, although he may be called out after hours, in
    emergencies.</p>
    
    <p>During the regular working hours, the Caretaker will conduct routine work and specific tasks,
    deemed needed by PPM.</p>
    
    <p>All requests for the Caretaker to conduct work should be sent to the PPM website or
    submitted in writing and posted to PPM though our mail-slot (Block 2). Please do not
    directly approach the caretaker to request work, although you are encouraged to introduce
    yourself to him.</p>
    
    <a href="#top" title="Return to the top of the page" class="page_nav"><i class="icon-arrow-up"></i>Back To Top</a>
    </div>
    
    <div class="span7">
    <a name="duties"></a><h2>Caretaker&#39;s Duties</h2>
    
    <strong>Security Of Premises</strong>
    <ul>
      <li>To be responsible for the security and maintenance of PPM equipment stored
          in common areas of the building, as far as is reasonably practicable.</li>
      <li>To ensure that common areas of the building are secured, including windows,
          gates and garages.</li>
      <li>To attend the building outside the normal working hours in the event of an
          emergency call-out and to take appropriate action in the event of such a
          call-out.</li>
      <li>To be responsible, where possible, for the boarding up of windows for
          security purposes (from inside).</li>
      <li>When appropriate to approach people on the PPM grounds and ensure that they are
          residents, visitors, or contracted workers.</li>
      <li>To take appropriate action (e.g. contact the authorities) if unwanted persons are on the
          premises.</li>
    </ul>
    
    <b>Cleaning Duties</b>
    <ul>
      <li>To undertake weekly cleaning of a specified areas within the building.</li>
      <li>To ensure that all cleaning equipment when used is properly cleaned and
          stored.</li>
      <li>To undertake the cleaning of special areas if required (as defined by the
          board).</li>
    </ul>
    
    <b>General Maintenance</b>
    <ul>
      <li>To carry out minor repairs of a DIY nature (that do not require
          specialist knowledge beyond the Caretaker&#39;s abilities).</li>
      <li>To ensure the provision of heating and lighting in communal areas as
          necessary and the checking of the same.</li>
      <li>To ensure that areas outside the building are tidy and litter free.</li>
      <li>To ensure basement areas, drains and gullies are tidy and litter-free
          including the cleaning of grease traps where appropriate.</li>
      <li>To remove snow from main entrances and to keep steps free of snow.</li>
      <li>To collect litter/leaves from grounds and gate area and remove to bin
          area.</li>
      <li>To liaise with external maintenance contractors and offer access to the
          building of all authorised trades people.</li>
      <li>To check boiler on a weekly basis.</li>
      <li>To ensure that entry phones are in full working order and liaise with
          contractor for repairs and servicing purposes.</li>
      <li>To inspect all water pipes weekly.</li>
      <li>To ensure that bin areas are clean and are free from obstruction on a
          daily basis.</li>
      <li>To carry out a daily visual inspection the building and address any
          issues.</li>
    </ul>
    
    <b>Stock Control</b>
    <ul>
      <li>To be responsible for the receipt of deliveries of goods and their
          transfer to the relevant storage area.</li>
      <li>To be responsible for stock rotation, issue and re-ordering of cleaning
          materials and basic consumables (e.g. light bulbs).</li>
    </ul>
    
    <b>Customer Care</b>
    <ul>
      <li>To effectively liaise with all building users so that everybody is treated
          with concern, consideration and care.
      <li>To take every opportunity to promote a favourable image to all building
          users.
    </ul>
    
    <b>Administration</b>
    <ul>
      <li>To ensure that staff attendance records are kept up to date and that
          timesheets submitted as required including the authorisation of holiday
          requests.
      <li>To ensure that all serious accidents occurring are reported to the
          Company Secretary, and that all accidents are reported correctly and
          logged in the accident book.
      <li>To ensure that tenant concerns and complaints are recorded and
          communicated to the board.
      <li>To ensure that general maintenance problems, damage or any other relevant
          problems are reported to the Company Secretary or chairperson.
    </ul>
    
    <b>Health &amp; Safety</b>
    <ul>
      <li>To ensure, as far as possible, that cleaning materials and all equipment are used in
          accordance with recommended practices and in a sensible and safe manner by the
          caretaker.</li>
      <li>To ensure as far as is reasonably practicable, that fire fighting
          equipment is effective, that fire exits are free from obstruction and in
          working order (in liaison with the Board), and to assist in
          fire drills.</li>
      <li>To ensure that all communal areas are free from obstruction and that
          walkways are free from potential hazards e.g. leaves, moss, rubbish.</li>
    </ul>
    
    <b>Gardening</b>
    <ul>
      <li>To undertaken regular maintenance and mowing of grassed areas.
      <li>To ensure that hedges are clipped and maintained.
      <li>To ensure that areas of the garden not tended to by shareholders are
          adequately maintained i.e. flower borders and that all weeds are removed.
    </ul>
    
    <p>Residents will be notified in writing if any changes are made to the
    caretaker&#39;s duties.</p>
    
    <a href="#top" title="Return to the top of the page" class="page_nav"><i class="icon-arrow-up"></i>Back To Top</a>
    <p>&nbsp;</p>
    </div>
</div>