<? $this->headTitle('Contact Us'); ?>

<a name="top"></a><h1>Contact Us</h1>

<!-- Chapter links -->

<p><i>On this page: </i>
<a href="#email" title="Jump to: By Email"
   class="page_nav">By Email</a> &raquo;
<a href="#post" title="Jump to: By Post"
   class="page_nav">By Post</a>
</p>

<a name="email"></a><h2>By Email</h2>

<p>Please correspond with PPMMCL via email, using
<a class="maillink" href="mailto:princesparkmansions@yahoo.co.uk">princesparkmansions@yahoo.co.uk</a></p>

<a href="#top" title="Return to the top of the page" class="page_nav"><i class="icon-arrow-up"></i>Back To Top</a>

<a name="post"></a><h2>By Post</h2>

<p><i>Correspondence:</i><br/>
Princes Park Mansions Management Company Ltd<br/>
PO Box 7-12<br/>
Princes Park Mansions<br/>
Croxteth Road<br/>
Liverpool<br/>
L8 3SA</p>

<p><i>Service Charge Cheques:</i><br/>
Princes Park Mansions Management Company Ltd<br/>
c/o Blundellsands Properties Ltd<br/>
Byron Road<br/>
Crosby<br/>
Liverpool<br/>
L23 8TH</p>

<a href="#top" title="Return to the top of the page" class="page_nav"><i class="icon-arrow-up"></i>Back To Top</a>
<p>&nbsp;</p>

