<? $this->headTitle('Forgotten Password'); ?>

<h1>Forgotten Password</h1>

<p>If you have forgotten the password that you use to access the site, please complete the form below.
Your password will then be emailed to you.</p>

<form enctype="application/x-www-form-urlencoded" method="post"
    action="<?= $this->form->getAction(); ?>"
    class="form-horizontal"
    novalidate>

    <div class="control-group <? if ($this->form->email->hasErrors()) echo 'error'; ?>">
        <label for="title" class="control-label">Email address:</label>
        <div class="controls">
            <input type="email" name="email" id="email" size="30" maxlength="50" autofocus required
                value="<?= $this->form->getValue('email'); ?>" />
            <?php
            foreach ($this->form->email->getMessages() as $msg) {
                echo '<span class="help-inline">' . $msg . '</span>';
            }
            ?>
            <p class="help-block"><?= $this->form->email->getDescription() ?></p>
        </div>
    </div>

    <div class="control-group <? if ($this->form->flatno->hasErrors()) echo 'error'; ?>">
        <label for="title" class="control-label">Flat number:</label>
        <div class="controls">
            <input type="text" name="flatno" id="flatno" size="5" maxlength="3" required
                value="<?= $this->form->getValue('flatno'); ?>" class="input-mini" />
            <?php
            foreach ($this->form->flatno->getMessages() as $msg) {
                echo '<span class="help-inline">' . $msg . '</span>';
            }
            ?>
            <p class="help-block"><?= $this->form->flatno->getDescription() ?></p>
       </div>
   </div>

   <div class="form-actions">
      <input type="submit" name="submit" id="submit" value="Request Password" class="btn btn-primary" />
      <input type="button" name="cancel" id="cancel" value="Cancel" onclick="location.href='/index';" class="btn" />
   </div>

</form>
