<?
   $this->headTitle('Gallery');
   $this->headScript()->appendFile('/js/jquery.fancybox-1.3.4.pack.js', 'text/javascript');
   $this->headLink()->appendStylesheet('/css/jquery.fancybox-1.3.4.css', 'screen');
?>
 
<a name="top"></a><h1>Gallery</h1>

<p>The pictures of Princes Park Mansions and the surrounding area shown
are stored on Flickr as part of the
<a href="http://www.flickr.com/groups/1381716@N21/pool/"
class="extlink">Princes Park Mansions Flickr Group</a>.  If you have photos
or pictures that you would like to have added to the Gallery, please email us at
<a class="maillink" href="mailto:webmaster@princes-park-mansions.org.uk">webmaster@princes-park-mansions.org.uk</a>.</p> 

<p>Click any image to view an enlargement.</p>

<div class="row">

<?php foreach ($this->flickrResults as $arrayPhoto): ?>

   <div class="span4 gallery-image">
   <a class="fancybox" href="<?= $arrayPhoto['mainuri'] ?>" title="<?= $arrayPhoto['title'] ?>"
        rel="fancybox">
   <img height="<?= $arrayPhoto['thumbheight'] ?>"
        width="<?= $arrayPhoto['thumbwidth'] ?>"
        src="<?= $arrayPhoto['thumburi'] ?>"
        alt="<?= $arrayPhoto['title'] ?>"
        title="<?= $arrayPhoto['title'] ?>" />
   </a>
   <div class="picture-title">"<?= $arrayPhoto['title'] ?>"</div>
   <div class="picture-owner">by <?= $arrayPhoto['owner'] ?></div>
   </div>

<?php endforeach; ?>

</div>

<a href="#top" title="Return to the top of the page" class="page_nav"><i class="icon-arrow-up"></i>Back To Top</a>
<p>&nbsp;</p>

<script type="text/javascript">
$(document).ready(function() {
    $("a.fancybox").fancybox({
        'transitionIn'  :   'fade',
        'transitionOut' :   'none',
        'speedIn'       :   1000, 
        'speedOut'      :   200, 
        'overlayShow'   :   true,
        'titlePosition' :   'outside'
    });
});
</script>
