<? 
   $this->headTitle('History');
   $this->headMeta()->appendName('keywords', 'wyatt papworth,richard vaughan yates,joseph paxton');
   $this->headScript()->appendFile('/js/jquery.fancybox-1.3.4.pack.js', 'text/javascript');
   $this->headLink()->appendStylesheet('/css/jquery.fancybox-1.3.4.css', 'screen');
?>

<a name="top"></a><h1>History</h1>

<!-- Chapter links -->

<p><i>On this page: </i>
<a href="#building" title="Jump to: The Building"
   class="page_nav">The Building</a> &raquo;
<a href="#development" title="Jump to: The Princes Park Development"
   class="page_nav">The Princes Park Development</a>
</p>

<a name="building"></a><h2>The Building</h2>

<div class="row">

<div class="span6">
    <p>Designed by Wyatt Papworth, the building was built in 1843 as a terrace of
    ten luxury houses. Set on an important site at the corner of Sefton Park Road
    and Croxteth Road, it formed an imposing part of the ambitious and innovative
    Princes Park development (described below). By 1912, the building had been
    converted into the apartments we know today.</p>
    
    <p>The South Front (facing on to Princes Park) has a basement and four storeys
    with a later fifth storey, making it the largest Victorian building in the area.
    The stuccoed building has distinctive iron balconies and the central Doric
    entrance with cornice and balustraded parapet.</p>
</div>

<div class="span6">
   <img src="/images/postcards/ppm-nodate-1.jpg" alt="Princes Park Mansions (date unknown)">
   <br />
   <p>Princes Park Mansions (date unknown)</p>
</div>

<a class="span12" href="#top" title="Return to the top of the page"
    class="page_nav"><i class="icon-arrow-up"></i>Back To Top</a>

</div>

<a name="development"></a><h2>The Princes Park Development</h2>

<div class="row">

<div class="span6">
   <img src="/images/postcards/princes-park-1908.jpg" alt="Princes Park, 1908">
   <br />
   <p>Princes Park, 1908</p>
</div>

<div class="span6">
    <p>By the 1840s Liverpool was fast becoming the greatest industrial city in
    England. A wealthy industrialist and town councillor, Richard Vaughan Yates,
    had speculatively purchased 97 acres of meadow and farmland around a mile and a
    half from the city centre. He wished to set aside around forty acres for a park,
    developing the remainder as exclusive housing in the form of terraces and single
    villas.</p>
    
    <p>Yates invited the great Joseph Paxton to develop the park (which would become
    known as Prince&#39;s Park in honour of the birth of the Prince of Wales in 1841).
    Work started in 1842 and continued throughout the following year. Princes Park
    was a forerunner of later Victorian parks, with its principle of exclusive
    housing built around the edges of the park on individual plots sold for profit.</p>
    
    <p>While the land plots sold far slower than Yates expected, and most of the
    proposed terraces were never built, it enabled Paxton to try out ideas he had
    been developing for years. As Paxton&#39;s first municipal design project, it was
    his prototype and set a pattern that would be developed and extended in all his
    future public projects. This makes the Princes Park development a landmark in
    Victorian - and civic park - design.</p>
</div>

</div>

<p>Click the images below to enlarge:</p>

<div class="row image-popup-strip">
<div class="span3"><?= $this->imagePopup('/images/postcards/ppm-1926.jpg', 'Princes Park Mansions, 1926'); ?></div>
<div class="span3"><?= $this->imagePopup('/images/postcards/ppm-1926-swan.jpg', 'Princes Park Mansions, 1926'); ?></div>
<div class="span3"><?= $this->imagePopup('/images/postcards/ppm-1916.jpg', 'Princes Park Mansions, 1916'); ?></div>
<div class="span3"><?= $this->imagePopup('/images/postcards/ppm-nodate-2.jpg', 'Princes Park Mansions (date unknown)'); ?></div>
</div>

<a href="#top" title="Return to the top of the page" class="page_nav"><i class="icon-arrow-up"></i>Back To Top</a>
<p>&nbsp;</p>

<script type="text/javascript">
$(document).ready(function() {
    $("a.fancybox").fancybox({
        'transitionIn'  :   'fade',
        'transitionOut' :   'none',
        'speedIn'       :   1000, 
        'speedOut'      :   200, 
        'overlayShow'   :   true,
        'titlePosition' :   'outside'
    });
});
</script>
