<? $this->headTitle('Home'); ?>

<div class="row">
<img class="span12" src="/images/building.jpg" width="620" alt="The Mansions" title="The Mansions" />
</div>

<a name="top"></a><h1>Welcome</h1>

<div class="row">

    <div class="span6">
    <p>Welcome to the Princes Park Mansions website. This site is always developing, and we are keen
    to hear suggestions for content, as well as general feedback about the site itself.</p>

    <p>Use the links at the top of the page to navigate to main site sections. By logging on you
    will be able to access additional content.  To get a username and password, please contact the
    email address below.</p>
    </div>
    
    <div class="span6">
    <p>Please email your suggestions and comments about the website to
    <a class="maillink" href="mailto:webmaster@princes-park-mansions.org.uk">
    webmaster@princes-park-mansions.org.uk</a></p>
    
    <p>If you are a new resident, please take a look at our
    <a class="doclink" target="_blank"
    href="/documents/shareholders/shareholder-tenant-welcome-pack-june2015.pdf">Shareholder &amp;
    Tenant Information Pack</a>. To download a copy, right-click the link and select "Save As".
    More documents are available for logged-on users.</p>
    </div>

</div>

<!-- Zend Version: <? echo Zend_Version::VERSION; ?> -->

<!-- APPLICATION_ENVIRONMENT: <? echo getenv('APPLICATION_ENVIRONMENT') ?> -->

<!-- SERVER_ADDR: <? echo getenv('SERVER_ADDR') ?> -->
