<? $this->headTitle('Management Company'); ?>

<a name="top"></a><h1>PPM Management Company Ltd</h1>

<!-- Chapter links -->

<p><i>On this page: </i>
<a href="#overview" title="Jump to: Overview"
   class="page_nav">Overview</a> &raquo;
<a href="#responsibilities" title="Jump to: Responsibilities"
   class="page_nav">Responsibilities</a> &raquo;
<a href="#charge" title="Jump to: Service Charge"
   class="page_nav">Service Charge</a> &raquo;
<a href="#regulations" title="Jump to: General Regulations"
   class="page_nav">General Regulations</a>
</p>

<a name="overview"></a><h2>Overview</h2>

<p>The company is responsible for the overall management and upkeep of the
building as stipulated within the lease. PPMMCL owns the freehold to the
property and when you purchase a flat within the mansions you are issued with
one share certificate. As a shareholder you are entitled to attend and vote at
the Annual General Meeting and receive regular bulletins regarding the
management of the building.</p>

<p>PPMMCL has been since November 2004 operating a self management model, which
has comprised a number of sub groups undertaking key areas of work on a
voluntary basis e.g. company secretary, finance and debt management, repairs and
renewals and employee support. The purpose of the self-management arrangement is
to reduce administration costs and to ensure that shareholders get best value
for their service charge.  New shareholders are welcome to join the board.</p>

<p>Princes Park Management Company Ltd is registered in England and Wales,
Company number: 1768248</p>

<a href="#top" title="Return to the top of the page" class="page_nav"><i class="icon-arrow-up"></i>Back To Top</a>

<a name="responsibilities"></a><h2>Responsibilities</h2>

<p>The management company&#39;s key responsibilities are to ensure:</p>

<ul>
  <li>There are effective financial management and service charge collection
      procedures in place.</li>
  <li>Compliance with company law, health and safety and current legislation
      requirements under the Commonhold and Leasehold Reform Act 2000.</li>
  <li>That essential repairs and an on going renewals programme is undertaken.</li>
  <li>Shareholder involvement and accountability.</li>
  <li>Effective utilisation of PPM assets.</li>
  <li>That there is consistent employee support and supervision.</li>
  <li>That shareholders concerns are dealt with in an efficient and
       professional manner.</li>
</ul>

<p>Visit our <a href="/index/contact" title="Go to Contact Us page">Contact
Us</a> page for ways to contact PPMMCL.</p>

<a href="#top" title="Return to the top of the page" class="page_nav"><i class="icon-arrow-up"></i>Back To Top</a>

<a name="charge"></a><h2>Service Charge</h2>

<p>Service charge payments are a condition of the lease and a must be paid to
PPMMCL. Non-payment of service charge can result in forfeiture of your lease and
PPMMCL can take ownership of you property. Service charge payments ensure that
the company can provide an onsite caretaker service, building insurance,
communal lighting and cleaning, grounds maintenance and undertake essential
repairs and renewals programme which will contribute to enhancing the value of
your property. Service charge levels are set each year by the board of
management and approved by shareholders at the AGM.</p>

<p>Service charge rates for the year 2012/13 are as follows:</p>

<table class="table table-striped table-condensed">
  <tr><td>Hot water monthly</td>
      <td>&pound;189.53</td>
      <td>x 12</td>
      <td>&pound;2,274.36</td></tr>
  <tr><td>Hot water half yearly</td>
      <td>&pound;1,083.10</td>
      <td>x 2</td>
      <td>&pound;2,166.20</td></tr>
  <tr><td>Without hot water monthly</td>
      <td>&pound;171.66</td>
      <td>x 12</td>
      <td>&pound;2,059.92</td></tr>
  <tr><td>Without hot water half yearly</td>
      <td>&pound;962.67</td>
      <td>x 2</td>
      <td>&pound;1,925.34</td></tr>
</table>

<p>Payments can be made by cheque to:</p>
<p>Princes Park Mansions Company Ltd<br/>
c/o Blundellsands Properties Ltd<br/>
Byron Road<br/>
Crosby<br/>
Liverpool<br/>
L23 8TH</p>

<p>Alternatively, payments can be made by standing order - bank details are avaialabe to residents on request.</p>

<p><i>Note:</i> Half year payments fall due on December 1st and June 1st and payment
must be made with 14 days of these due dates or payments will be calculated
as if payment was being on a monthly basis. Service charge arrears are subject
to 12% interest fee, which will be added to your statement. Non-payment of
service charge will result in legal action.</p>

<a href="#top" title="Return to the top of the page" class="page_nav"><i class="icon-arrow-up"></i>Back To Top</a>

<a name="regulations"></a><h2>General Regulations</h2>

<p>See the <a href="/index/regulations">Regulations</a> page.</p>

<a href="#top" title="Return to the top of the page" class="page_nav"><i class="icon-arrow-up"></i>Back To Top</a>
<p>&nbsp;</p>
