<? 
   $this->headTitle('Regulations');
?>

<a name="top"></a><h1>Regulations</h1>

<a name="general"></a><h2>General Regulations</h2>

<ul>
    <li>Flats usage must be confined to private use only.</li>
    <li>Residents must ensure that noise levels - either in communal areas or individual flats
    - do not disturb their neighbours.</li>
    <li>Residents must ensure that all gates and doors are locked to provide maximum
    security.</li>
    <li>The garden is for the use and enjoyment of all residents; please consider your
    neighbours in relation to noise levels and ensure that all litter is removed, that
    communal tables and chairs are stored in the basement areas after use, and that the
    gazebo is returned to the garden shed.</li>
    <li>If a party is to be held in the garden area, the organiser should contact the
    Management Company, so that they may indicate the event to other Shareholders.
    Noise at parties should be kept to a reasonable level, especially in the evenings.</li>
    <li>Pet owners need to ensure that their pets are kept under control and do not cause
    damage to the internal hallways or garden area.</li>
    <li>Hallways, staircases, and corridors are fire escapes and must be kept clear at all times.</li>
    <li>The integrity of the metal balconies is being investigated as part of repair plans for the
    building: until we receive assurances from the engineers you should not use them for
    any purpose.</li>
    <li>All bicycles must be stored within flats or in the bike shed. Bicycles must not be
    chained to railing areas or stored in the hallways. The only exception to this is that
    bicycles may be locked to the one "bent" railing at the city side of the building near
    the garages. However, bicycles must never be left there overnight, but only for short
    periods during the day.</li>
    <li>Use of the lift for the carriage of heavy goods by trades people is prohibited. Lift
    usage by unaccompanied minors is prohibited.</li>
    <li>Please keep all rubbish areas clean by depositing rubbish in appropriate bins.</li>
    <li>Please put only appropriate material in recycling bins.</li>
</ul>

<a href="#top" title="Return to the top of the page" class="page_nav"><i class="icon-arrow-up"></i>Back To Top</a>
<p>&nbsp;</p>