<? $this->headTitle('Add Document');
   $this->headScript()->appendFile('/js/jquery-ui-1.8.7.custom.min.js', 'text/javascript');
   $this->headLink()->appendStylesheet('/css/jquery-ui-1.8.7.custom.css', 'screen');
?>

<script type="text/javascript">
<!--
   var typePaths = new Array();
   
<?php
   foreach ($this->documentTypes as $typ) {
      echo "typePaths[" . $typ['id'] . "] = '" . $typ['folder'] . "';";
   }
?>

$.datepicker.setDefaults({
   showOn: 'both',
   buttonImageOnly: true,
   buttonImage: '/images/calendar.gif',
   buttonText: 'Calendar' });

$(function() {
  $( "#doc_date" ).datepicker();
  $( "#doc_date" ).datepicker( "option", "dateFormat", "dd/mm/yy");
  if ('<?= $this->form->getValue('doc_date'); ?>' != '') {
	    $( "#doc_date" ).datepicker("setDate", '<?= $this->form->getValue('doc_date'); ?>');
  }
});

function dtypeChanged() {
   document.getElementById('doc_folder').value = typePaths[document.getElementById('doc_type').value];
}
//-->
</script>

<h1>Add Document</h1>

<p><strong>Note:</strong> Document types denoted with an asterisk (*) are visible to Shareholders
accessing this site (but they cannot add documents).</p>

<form enctype="multipart/form-data" method="post"
    action="<?= $this->form->getAction(); ?>"
    class="form-horizontal"
    novalidate>

<fieldset>

   <input type="hidden" name="id" value="<?= $this->form->getValue('id'); ?>" id="id" />
   
    <div class="control-group <? if ($this->form->doc_type->hasErrors()) echo 'error'; ?>">
        <label for="doc_type" class="control-label">Type:</label>
        <div class="controls">
            <select name="doc_type" id="doc_type" onchange="dtypeChanged();" autofocus>
                <option value="0">Select...</option>
              <?php
                 foreach ($this->documentTypes as $typ) {
                 	$selectOption = '<option ';
                    if ($typ['id'] == $this->form->getValue('doc_type')) {
                        $selectOption .= 'selected ';
                    }
                    $selectOption .= 'value="' . $typ['id'] . '">';
                    $selectOption .= $typ['name'];
                    if ($typ[flag] > 0) {
                    	$selectOption .= ' *';
                    }
                    $selectOption .= '</option>';
                    
                    echo $selectOption;
                 }
              ?>
            </select>
            <?php
            foreach ($this->form->doc_type->getMessages() as $msg) {
                echo '<span class="help-inline">' . $msg . '</span>';
            }
            ?>
            <p class="help-block"><?= $this->form->doc_type->getDescription() ?></p>
        </div>
   </div>

    <div class="control-group <? if ($this->form->title->hasErrors()) echo 'error'; ?>">
        <label for="title" class="control-label">Title:</label>
        <div class="controls">
            <input type="text" name="title" id="title" size="50" maxlength="100" required
                value="<?= $this->form->getValue('title'); ?>" />
            <?php
            foreach ($this->form->title->getMessages() as $msg) {
                echo '<span class="help-inline">' . $msg . '</span>';
            }
            ?>
            <p class="help-block"><?= $this->form->title->getDescription() ?></p>
        </div>
   </div>

    <div class="control-group <? if ($this->form->filename->hasErrors()) echo 'error'; ?>">
        <label for="filename" class="control-label">File:</label>
        <div class="controls">
      
      <?php
         $ppm_session = new Zend_Session_Namespace('ppm');
         $registry = Zend_Registry::getInstance();
         $acl = $registry->acl;
         if (isset($ppm_session->user)) {
            $u = $ppm_session->user;
         }
      ?>
      <? if ($acl->isallowed($u->getRole(), 'document', 'largefiles')): ?>
         <input type="hidden" name="MAX_FILE_SIZE" value="10245760" id="MAX_FILE_SIZE" />
      <? else: ?>
         <input type="hidden" name="MAX_FILE_SIZE" value="5242880" id="MAX_FILE_SIZE" />
      <? endif; ?>
      
            <input type="file" name="filename" id="filename" value="<?= $this->form->getValue('filename'); ?>" />
            <?php
            foreach ($this->form->filename->getMessages() as $msg) {
                echo '<span class="help-inline">' . $msg . '</span>';
            }
            ?>
            <p class="help-block"><?= $this->form->filename->getDescription() ?></p>
        </div>
   </div>
   
   <input type="hidden" id="doc_folder" name="doc_folder" />

    <div class="control-group <? if ($this->form->doc_date->hasErrors()) echo 'error'; ?>">
        <label for="doc_date" class="control-label">Document Date:</label>
        <div class="controls">
            <input type="text" name="doc_date" id="doc_date" size="10" maxlength="10" required
                value="<?= $this->form->getValue('doc_date'); ?>" class="input-mini" />
            <?php
            foreach ($this->form->doc_date->getMessages() as $msg) {
                echo '<span class="help-inline">' . $msg . '</span>';
            }
            ?>
            <p class="help-block"><?= $this->form->doc_date->getDescription() ?></p>
        </div>
   </div>

   <div class="form-actions">
      <input type="submit" name="submit" id="submit" value="Save" class="btn btn-primary" />
      <input type="button" name="cancel" id="cancel" value="Cancel" onclick="location.href='/document';" class="btn" />
   </div>
   
   </fieldset>

</form>
