<? $this->headTitle('Document Centre'); ?>

<?
$ppm_session = new Zend_Session_Namespace('ppm');
$registry = Zend_Registry::getInstance();
$acl = $registry->acl;
$u = $ppm_session->user;

$this->headLink()->appendStylesheet('/css/paginator.css', 'screen');
?>

<a name="top"></a>
<h1>Document Centre</h1>

<p>This page contains documents in the Portable Document Format (PDF). The
software used to allow you to read PDFs is free.  If you do not already have a
PDF reader, click the icon below.</p>

<div><a href="http://www.adobe.com/products/acrobat/readstep2.html"
        target="_blank">
<img src="/images/getacro.gif"
     alt="Get Acrobat Reader web logo"
     title="Get Adobe Reader" /></a></div>
     
<p>To view the documents, simply click the title.</p>

<form action="/document/index" method="post" class="form-inline">

<fieldset>
   
   <div class="control-group">
   <label for="doc_type" class="control-label">Filter:</label>
   <div class="controls">
   <select name="doc_type" id="doc_type">
      <option value="0">All Types</option>
      <?php
         foreach ($this->documentTypes as $typ) {
            if ($typ['id'] == $this->form->getValue('doc_type')) {
               echo '<option selected value="' . $typ['id'] . '">' . $typ['name'] . '</option>';
            } else {
               echo '<option value="' . $typ['id'] . '">' . $typ['name'] . '</option>';
            }
         }
      ?>
   </select>
   </div>
   
   <div class="control-group">
   <label for="doc_date" class="control-label">Age:</label>
   <div class="controls">
   <select name="doc_date" id="doc_date" class="input-medium">
      <?php
         foreach ($this->dateTypes as $typ) {
            if ($typ['id'] == $this->form->getValue('doc_date')) {
               echo '<option selected value="' . $typ['id'] . '">' . $typ['name'] . '</option>';
            } else {
               echo '<option value="' . $typ['id'] . '">' . $typ['name'] . '</option>';
            }
         }
      ?>
   </select>
   </div>
   </div>

   <div class="control-group">
   <label for="doc_title" class="control-label">Title contains:</label>
   <div class="controls">
   <input type="text" name="doc_title" id="doc_title" size="10" class="input-medium" />
   <input class="btn btn-mini" type="submit" value="Filter" />
   </div>
   </div>

</fieldset>   

</form>

<? if ($acl->isAllowed($u->getRole(), 'document', 'add')): ?>
<button name="addDocument"
   title="Add a new document" class="btn btn-mini"
   onclick="javascript:document.location='/document/add'">Add Document...</button>
<? endif; ?>

<div class="list">

<?php if (count($this->paginator) == 0): ?>
    <div class="alert alert-warn">
    <strong>Note:</strong> No documents found.
    </div>
<?php else: ?>

<style>
@media only screen and (max-width: 760px),
(min-device-width: 768px) and (max-device-width: 1024px)  {

    /* Force table to not be like tables anymore */
    table, thead, tbody, th, td, tr { 
        display: block; 
    }
    
    /* Hide table headers (but not display: none;, for accessibility) */
    thead { 
        position: absolute;
        top: -9999px;
        left: -9999px;
    }
    
    tr {
        border: 1px solid #ccc;
        margin-bottom: 1em;
    }
    
    td { 
        /* Behave  like a "row" */
        border: none;
        border-bottom: 1px solid #eee; 
        position: relative;
        padding-left: 50%; 
    }
    
    td:before { 
        /* Now like a table header */
        /* Top/left values mimic padding */
        top: 6px;
        left: 6px;
        width: 45%; 
        padding-right: 10px; 
        white-space: nowrap;
        font-weight: bold;
    }
    
    /*
    Label the data
    */
    td:nth-of-type(1):before { content: "Type:"; }
    td:nth-of-type(2):before { content: "Date:"; }
    td:nth-of-type(3):before { content: "Title:"; }
    td:nth-of-type(4):before { content: "Size:"; }
}
</style>

    <!-- Loop through the entries that were provided to us by the controller -->
    <table class="table table-striped table-condensed">
        <thead>
        <tr>
            <th>Type</th>
            <th>Date</th>
            <th>Title</th>
            <th>Size</th>
            <th></th>
        </tr>
        </thead>

   <?php $counter = 0; ?>
   <?php foreach ($this->paginator as $entry):?>

      <tr>
         <td>
            <?php echo $this->escape($entry['name']) ?>
         </td>
         <td>
            <?php echo $this->escape($entry['dated']) ?>
         </td>
         <td>
            <a class="doclink" target="_blank" href="<?php echo $entry['folder'] . DIRECTORY_SEPARATOR . $entry['path'] ?>"><?php echo $entry['title'] ?></a>
         </td>
         <td>
            (<?php echo $this->escape($entry['size']) ?>K)
         </td>
         <td>
         <? if ($acl->isAllowed($u->getRole(), 'document', 'delete')): ?>
               <a class="btn btn-danger btn-mini"
                  name="deleteDocument"
                  title="Delete this document"
                  href="<?= $this->url(array('controller' => 'document', 'action' => 'delete', 'id' => $entry['id'], 'title' => $entry['title'])) ?>">Delete</a>
         <? endif; ?>
         </td>
      </tr>
         
   <?php endforeach;?>
   </table>
   
   <?php echo $this->paginationControl($this->paginator, 'Sliding',  'paginator.phtml'); ?>
   
<?php endif; ?>

</div>

<a href="#top" title="Return to the top of the page" class="page_nav"><i class="icon-arrow-up"></i>Back To Top</a>
<p>&nbsp;</p>
