<?
   $this->headScript()->appendFile('/js/jquery-ui-1.8.9.custom.min.js', 'text/javascript'); 
   $this->headLink()->appendStylesheet('/css/jquery-ui-1.8.9.custom.css', 'screen');
?>

<script>
$.datepicker.setDefaults({
   showOn: 'both',
   buttonImageOnly: true,
   buttonImage: '/images/calendar.gif',
   buttonText: 'Calendar' });

function fixDate(oldDate) {
	if (oldDate.indexOf('-') != -1) {
      dateComponents = oldDate.split('-');
	  return dateComponents[2] + '/' + dateComponents[1] + '/' + dateComponents[0];
	}
	return oldDate;
}

$(function() {
  $( "#date_requested, #date_completed" ).datepicker();
  $( "#date_requested, #date_completed" ).datepicker( "option", "dateFormat", "dd/mm/yy");
  
  if ('<?= $this->form->getValue('date_requested'); ?>' == '') {
    $( "#date_requested" ).datepicker("setDate", "+0");
  } else {
	$( "#date_requested" ).datepicker("setDate", fixDate('<?= $this->form->getValue('date_requested'); ?>'));
  }
  if ('<?= $this->form->getValue('date_completed'); ?>' != '') {
    $( "#date_completed" ).datepicker("setDate", fixDate('<?= $this->form->getValue('date_completed'); ?>'));
  }
});

</script>

<form enctype="application/x-www-form-urlencoded" method="post"
    action="<?= $this->form->getAction(); ?>"
    class="form-horizontal"
    novalidate>

<fieldset>
   <input type="hidden" name="id" value="<?= $this->form->getValue('id'); ?>" id="id" />

    <div class="control-group <? if ($this->form->title->hasErrors()) echo 'error'; ?>">
        <label for="title" class="control-label"><?= $this->form->title->getLabel() ?></label>
        <div class="controls">
            <input type="text" name="title" id="title" size="50" maxlength="50" autofocus
                value="<?= $this->form->getValue('title'); ?>" required />
            <?php
            foreach ($this->form->title->getMessages() as $msg) {
                echo '<span class="help-inline">' . $msg . '</span>';
            }
            ?>
            <p class="help-block"><?= $this->form->title->getDescription() ?></p>
        </div>
   </div>

    <div class="control-group <? if ($this->form->notes->hasErrors()) echo 'error'; ?>">
        <label for="notes" class="control-label"><?= $this->form->notes->getLabel() ?></label>
        <div class="controls">
            <textarea name="notes" id="notes" rows="10" cols="50" required><?= $this->form->getValue('notes'); ?></textarea>
            <?php
            foreach ($this->form->notes->getMessages() as $msg) {
                echo '<span class="help-inline">' . $msg . '</span>';
            }
            ?>
            <p class="help-block"><?= $this->form->notes->getDescription() ?></p>
        </div>
   </div>

    <div class="control-group <? if ($this->form->priority->hasErrors()) echo 'error'; ?>">
        <label for="priority" class="control-label"><?= $this->form->priority->getLabel() ?></label>
        <div class="controls">
            <input type="text" name="priority" id="priority" size="5" maxlength="2"
                value="<?= $this->form->getValue('priority'); ?>" />
            <?php
            foreach ($this->form->priority->getMessages() as $msg) {
                echo '<span class="help-inline">' . $msg . '</span>';
            }
            ?>
            <p class="help-block"><?= $this->form->priority->getDescription() ?></p>
        </div>
   </div>

    <div class="control-group <? if ($this->form->date_requested->hasErrors()) echo 'error'; ?>">
        <label for="date_requested" class="control-label"><?= $this->form->date_requested->getLabel() ?></label>
        <div class="controls">
            <input type="text" name="date_requested" id="date_requested" size="10" maxlength="10"
                value="<?= $this->form->getValue('date_requested'); ?>" class="input-mini" />
            <?php
            foreach ($this->form->date_requested->getMessages() as $msg) {
                echo '<span class="help-inline">' . $msg . '</span>';
            }
            ?>
            <p class="help-block"><?= $this->form->date_requested->getDescription() ?></p>
        </div>
   </div>

    <div class="control-group <? if ($this->form->requested_by->hasErrors()) echo 'error'; ?>">
        <label for="requested_by" class="control-label"><?= $this->form->requested_by->getLabel() ?></label>
        <div class="controls">
            <input type="text" name="requested_by" id="requested_by" size="50" maxlength="100"
                value="<?= $this->form->getValue('requested_by'); ?>" required />
            <?php
            foreach ($this->form->requested_by->getMessages() as $msg) {
                echo '<span class="help-inline">' . $msg . '</span>';
            }
            ?>
            <p class="help-block"><?= $this->form->requested_by->getDescription() ?></p>
        </div>
   </div>

    <div class="control-group <? if ($this->form->assigned_to->hasErrors()) echo 'error'; ?>">
        <label for="assigned_to" class="control-label"><?= $this->form->assigned_to->getLabel() ?></label>
        <div class="controls">
            <select name="assigned_to" id="assigned_to">
                <option value="0">Select...</option>
                  <?php
                     foreach ($this->assignees as $ass) {
                        if ($ass['id'] == $this->form->getValue('assigned_to')) {
                           echo '<option selected value="' . $ass['id'] . '">' . $ass['name'] . '</option>';
                        } else {
                           echo '<option value="' . $ass['id'] . '">' . $ass['name'] . '</option>';
                        }
                     }
                  ?>
            </select>
            <?php
            foreach ($this->form->assigned_to->getMessages() as $msg) {
                echo '<span class="help-inline">' . $msg . '</span>';
            }
            ?>
            <p class="help-block"><?= $this->form->assigned_to->getDescription() ?></p>
        </div>
   </div>

    <div class="control-group <? if ($this->form->date_completed->hasErrors()) echo 'error'; ?>">
        <label for="date_completed" class="control-label"><?= $this->form->date_completed->getLabel() ?></label>
        <div class="controls">
            <input type="text" name="date_completed" id="date_completed" size="10" maxlength="10"
                value="<?= $this->form->getValue('date_completed'); ?>" class="input-mini" />
            <?php
            foreach ($this->form->date_completed->getMessages() as $msg) {
                echo '<span class="help-inline">' . $msg . '</span>';
            }
            ?>
            <p class="help-block"><?= $this->form->date_completed->getDescription() ?></p>
        </div>
   </div>

    <div class="control-group <? if ($this->form->effort->hasErrors()) echo 'error'; ?>">
        <label for="effort" class="control-label"><?= $this->form->effort->getLabel() ?></label>
        <div class="controls">
            <input type="text" name="effort" id="effort" size="5" maxlength="2"
                value="<?= $this->form->getValue('effort'); ?>" />
            <?php
            foreach ($this->form->effort->getMessages() as $msg) {
                echo '<span class="help-inline">' . $msg . '</span>';
            }
            ?>
            <p class="help-block"><?= $this->form->effort->getDescription() ?></p>
        </div>
   </div>

    <div class="control-group <? if ($this->form->cost->hasErrors()) echo 'error'; ?>">
        <label for="cost" class="control-label"><?= $this->form->cost->getLabel() ?></label>
        <div class="controls">
            <input type="text" name="cost" id="cost" size="5" maxlength="10"
                value="<?= $this->form->getValue('cost'); ?>" />
            <?php
            foreach ($this->form->cost->getMessages() as $msg) {
                echo '<span class="help-inline">' . $msg . '</span>';
            }
            ?>
            <p class="help-block"><?= $this->form->cost->getDescription() ?></p>
        </div>
   </div>

   <div class="form-actions">
      <input type="submit" name="submit" id="submit" value="Save" class="btn btn-primary" />
      <input type="button" name="cancel" id="cancel" value="Cancel" onclick="location.href='/task';" class="btn" />
   </div>

</fieldset>
</form>

