
DELETE FROM task;
DELETE FROM message;
DELETE FROM audit;
DELETE FROM contractor;
DELETE FROM document;
DELETE FROM work_record;
DELETE FROM flat_resident;
DELETE FROM resident;
DELETE FROM resident_list;

INSERT INTO resident_list (id, name, e_contact, email, password, role, flat, status) VALUES
(1, 'Andy Speakman', 'Y', 'andy.speakman@gmail.com', '5p34k3r5', 'admin', '4', 1),
(2, 'Nadine Hope', 'Y', 'nadine.hope@locall.net', 'salieri', 'shareholder', '27', 1),
(3, 'Peter Bates', 'Y', 'peter.bates9@btinternet.com', 'Howells1892', 'director', '30B', 1),
(4, 'Maggie O''Carroll', 'Y', 'maggieocarroll@yahoo.com', 'cjcregg', 'director', '7', 1),
(5, 'Nick Howe', 'Y', 'nick.howe@uniform.net', 'lampshades', 'shareholder', '32', 1),
(6, 'Gill Morgan', 'Y', 'morgangill87@yahoo.co.uk', 'alexpaula', 'director', '30A', 1),
(7, 'Emma Funnell', 'Y', 'emmamacnair@doctors.org.uk', 'ppm7b', 'director', '7B', 1),
(8, 'Paul Foster', 'Y', 'pfoster23@yahoo.co.uk', 'mansions', 'shareholder', '23', 1),
(9, 'Alun Jones', 'Y', 'alunlj@hotmail.com', 'jasper', 'shareholder', '2', 1),
(10, 'Lis Davidson', 'Y', 'lisdavidson@yahoo.co.uk', 'niC01efry', 'director', '34', 1),
(11, 'Frederick Jones', 'Y', 'fjones@liverpool.ac.uk', 'modudoxx', 'shareholder', '28', 1),
(12, 'Christine Ruth', 'Y', 'caruthchris@aol.com', 'florio', 'shareholder', '15', 1),
(13, 'Barbara Shields', 'Y', 'barbarashields@btinternet.com', 'barbara', 'shareholder', '2B', 1),
(14, 'Phil Cullen', 'Y', 'poornaseva@gmail.com', 'selenium', 'shareholder', '30', 1),
(15, 'Ron Stewart', 'Y', 'ronram.stewart1@btinternet.com', 'ronramstewart', 'shareholder', '24', 1),
(16, 'Test Shareholder', 'N', 'testshareholder@ppm.com', 'testshareholder', 'shareholder', '99', 1),
(17, 'Test Director', 'N', 'testdirector@ppm.com', 'testdirector', 'director', '99', 1),
(18, 'George Kidd', 'Y', 'gkidd@fastmail.fm', 'qwerty123', 'shareholder', '99', 1),
(19, 'Alice Ferrebe', 'Y', 'alice.ferrebe@btinternet.com', 'mungochild', 'shareholder', '11', 1),
(20, 'Mr Neil Sharrocks', 'N', NULL, NULL, NULL, '1A', 1),
(22, 'Ms Gill Ridpath', 'Y', 'gridpath@btinternet.com', 'password', 'shareholder', '3', 1),
(23, 'Ms Alex Robinson', 'Y', 'alexandra.robinson@liverpool.ac.uk', 'password', 'director', '4A', 1),
(24, 'David Montagnes', 'Y', 'dmontag@liv.ac.uk', 'montagnes', 'director', '5', 1),
(25, 'Mr Richard West', 'Y', 'rwandec@aol.com', 'MASHAM', 'shareholder', '6', 1),
(26, 'Saville Estate', 'N', NULL, NULL, NULL, '33', 1),
(27, 'Mr Christopher Cook', 'Y', 'leoclericus@aol.com', NULL, NULL, '8', 1),
(28, 'Ms Liz Mullin', 'Y', 'lizmullin7@googlemail.com', NULL, NULL, '9', 1),
(29, 'Mr Mark Bland', 'N', NULL, NULL, NULL, '10', 1),
(30, 'Spencer Property Developments Ltd', 'N', NULL, NULL, NULL, '12', 1),
(32, 'Mr Redmond', 'N', NULL, NULL, NULL, '14', 1),
(35, 'Ms Janet Garland', 'Y', 'janetgarland17@yahoo.co.uk', NULL, 'director', '17', 1),
(36, 'Dr Tom Aust', 'N', NULL, NULL, NULL, '18', 1),
(37, 'Mr Edgar Jones', 'Y', 'edgarjonesjones@hotmail.co.uk', NULL, NULL, '19', 1),
(38, 'Mr Jack Ashort', 'N', NULL, NULL, NULL, '20', 1),
(39, 'Mr John Benson', 'Y', 'johntbenson@hotmail.com', 'spuntini1', 'director', '21', 1),
(40, 'Mr Richard Jones', 'N', NULL, NULL, NULL, '22', 1),
(41, 'Mr Mike Doyle', 'N', NULL, NULL, NULL, '24', 1),
(42, 'Mrs Gina Grunenberg', 'Y', 'gina.grunenberg@gmx.de', 'henny0151', 'shareholder', '25', 1),
(43, 'Mr Judge', 'N', NULL, NULL, NULL, '26', 1),
(44, 'Mr Reg Mitton', 'N', NULL, NULL, NULL, '29', 1),
(45, 'Ms Carrol Wilson', 'Y', 'wilson31ppm@yahoo.co.uk', NULL, NULL, '31', 1),
(46, 'Ms Annie Davies', 'N', NULL, NULL, NULL, '31A', 1),
(47, 'Ms Helen Blyth', 'Y', 'now_then1@yahoo.co.uk', NULL, NULL, '35', 1),
(48, 'Ms Margie Marc-Naya', 'Y', 'margiemarc@gmail.com', 'urarin', 'shareholder', '1', 1),
(49, 'Shaaron Moon', 'N', 'shaaron.moon@btconnect.com', 'blundellsands', 'director', '99', 1),
(52, 'Thomas Nener', 'N', NULL, NULL, NULL, '16', 1),
(53, 'Patricia Gibson', 'N', NULL, NULL, NULL, '16', 1),
(54, 'Fiona Hobden', 'Y', 'f.hobden@liv.ac.uk', NULL, NULL, '5', 1),
(55, 'Elizabeth Cain', 'N', NULL, NULL, NULL, '6', 1),
(56, 'James Trafford', 'Y', 'james.trafford1@btinternet.com', 'douglas210910', 'director', '11', 1),
(57, 'Miss Carroll', 'N', NULL, NULL, NULL, '17', 1),
(58, 'Miss Thompson', 'N', NULL, NULL, NULL, '22', 1),
(59, 'Helen Green', 'N', NULL, NULL, NULL, '23', 1),
(60, 'Christoph Grunenberg', 'N', NULL, NULL, NULL, '25', 1),
(61, 'Philip Daniel', 'N', NULL, NULL, NULL, '27', 1),
(62, 'Ms Nolan', 'N', NULL, NULL, NULL, '30A', 1),
(63, 'Sowena Nelson', 'Y', 'sowenanelson@aol.com', NULL, NULL, '18', 1),
(64, 'Greg Madden', 'N', NULL, NULL, NULL, '18', 1),
(65, 'Giulia Harding', 'Y', 'giulia.harding@googlemail.com', NULL, NULL, '33', 1),
(66, 'Julia Mesa', 'Y', 'juliamesa@hotmail.co.uk', NULL, NULL, '20', 1),
(67, 'Margaret Ashort', 'N', NULL, NULL, NULL, '20', 1),
(68, 'Michelle Monti', 'N', 'michelle@bluevision.uk.com', NULL, NULL, '26', 1),
(69, 'Una O''Kane', 'Y', 'oonsaboonsa@yahoo.co.uk', NULL, NULL, '26', 1),
(75, 'Daniel Cadena (Caretaker)', 'N', 'danielrodriguezcadena@yahoo.com', 'pa55word', 'caretaker', '99', 1),
(71, 'Anna Beaumont', 'Y', 'anna@icecreates.com', NULL, NULL, '7B', 1),
(72, 'Becky Turner', 'Y', 'roundfatface@hotmail.com', NULL, NULL, '7B', 1),
(73, 'Kim Sacker', 'N', NULL, NULL, NULL, '1A', 1),
(74, 'Lucy Byrne', 'Y', 'lucy.byrne@dot-art.co.uk', NULL, NULL, '4', 1),
(76, 'Ann Marie Jones', 'Y', 'amj357@hotmail.co.uk', 'password', 'director', '2', 1),
(77, 'Doreen McCaghey', 'Y', 'doreenmccaghey@googlemail.com', 'd0r33n', 'shareholder', '7A', 1),
(78, 'Claire Bates', 'Y', 'landbabyshop@gmail.com', NULL, 'shareholder', '7A', 1),
(79, 'Donovan Collins', 'Y', 'dcollins@merseyrail.org', NULL, NULL, '12', 1),
(80, 'Melanie Hill', 'Y', 'melaniejanehill@googlemail.com', NULL, 'shareholder', '32', 1),
(81, 'Mary Redmond', 'Y', 'maryredmond@care4free.net', 'maryredmond', 'shareholder', '14', 1);
