<?
   $this->headScript()->appendFile('/js/jquery-ui-1.8.7.custom.min.js', 'text/javascript'); 
   $this->headLink()->appendStylesheet('/css/jquery-ui-1.8.7.custom.css', 'screen');
?>

<script>
$.datepicker.setDefaults({
   showOn: 'both',
   buttonImageOnly: true,
   buttonImage: '/images/calendar.gif',
   buttonText: 'Calendar' });

function fixDate(oldDate) {
	if (oldDate.indexOf('-') != -1) {
      dateComponents = oldDate.split('-');
	  return dateComponents[2] + '/' + dateComponents[1] + '/' + dateComponents[0];
	}
	return oldDate;
}

$(function() {
  $( "#date_expires" ).datepicker();
  $( "#date_expires" ).datepicker( "option", "dateFormat", "dd/mm/yy");
  if ('<?= $this->form->getValue('date_expires'); ?>' != '') {
    $( "#date_expires" ).datepicker("setDate", fixDate('<?= $this->form->getValue('date_expires'); ?>'));
  }
});
</script>

<form enctype="application/x-www-form-urlencoded" method="post"
    action="<?= $this->form->getAction(); ?>"
    class="form-horizontal"
    novalidate>

<fieldset>
    <input type="hidden" name="id" value="<?= $this->form->getValue('id'); ?>" id="id" />

    <div class="control-group <? if ($this->form->title->hasErrors()) echo 'error'; ?>">
        <label for="title" class="control-label">Title:</label>
        <div class="controls">
            <input type="text" name="title" id="title" maxlength="50" class="span6" autofocus required
                value="<?= $this->form->getValue('title'); ?>" />
            <?php
            foreach ($this->form->title->getMessages() as $msg) {
                echo '<span class="help-inline">' . $msg . '</span>';
            }
            ?>
            <p class="help-block"><?= $this->form->title->getDescription() ?></p>
        </div>
   </div>

    <div class="control-group <? if ($this->form->notes->hasErrors()) echo 'error'; ?>">
        <label for="notes" class="control-label">Message:</label>
        <div class="controls">
            <textarea name="notes" id="notes" rows="10" class="span6" required><?= $this->form->getValue('notes'); ?></textarea>
            <?php
            foreach ($this->form->notes->getMessages() as $msg) {
                echo '<span class="help-inline">' . $msg . '</span>';
            }
            ?>
            <p class="help-block"><?= $this->form->notes->getDescription() ?></p>
        </div>
   </div>

    <div class="control-group <? if ($this->form->date_expires->hasErrors()) echo 'error'; ?>">
        <label for="date_expires" class="control-label">Expiry Date:</label>
        <div class="controls">
            <input type="text" name="date_expires" id="date_expires" size="10" maxlength="10"
                value="<?= $this->form->getValue('date_expires'); ?>" class="input-small" />
            <?php
            foreach ($this->form->date_expires->getMessages() as $msg) {
                echo '<span class="help-inline">' . $msg . '</span>';
            }
            ?>
            <p class="help-block"><?= $this->form->date_expires->getDescription() ?></p>
        </div>
   </div>

   <div class="form-actions">
      <input type="submit" name="submit" id="submit" value="Save" class="btn btn-primary" />
      <input type="button" name="cancel" id="cancel" value="Cancel" onclick="location.href='/message';" class="btn" />
   </div>

</fieldset>
</form>

