<? $this->headTitle('Insurance Issues'); ?>

<a name="top"></a><h1>Insurance Issues</h1>

<!-- Chapter links -->

<p><i>On this page: </i>
<a href="#damage" title="Jump to: Damage To Your Flat - What Should You Do?"
   class="page_nav">Damage To Your Flat - What Should You Do?</a>
</p>

<a name="damage"></a><h2>Damage To Your Flat - What Should You Do?</h2>

<p>This section of the website includes help and advice if you have problems with the structure of
your flat - the walls, the ceiling, the floor, the windows. It does not include problems with the
moveable contents of your flat (unless that affects other people).</p>

<h3>Was the damage caused by your action (or your inaction)?</h3>

<ul>
   <li>The Princes Park Management Company Ltd (&quot;PPM Ltd&quot;) cannot take any responsibility for this
   - you need to contact your own insurers.</li>
   <li>You should make sure that your insurance is adequate in case damage within your flat affects
   other flats, or damages the common parts of the building owned by PPM Ltd, because people may
   wish to recover their costs from you.</li>
   <li>If things are urgent or dangerous, PPM Ltd&#39;s caretaker and directors will do what they
   can to help, especially if this reduces damage outside of your flat. You should contact Gail as
   soon as possible.</li>
   <li>This website contains a list of tradespeople that have carried out works for PPM Ltd in the
   past. If people are included (or excluded) from that list this doesn&#39;t imply any judgement
   by PPM Ltd of the quality or value for money of their work. However this list may be useful to
   you, as all those people have some experience with the building and its unique layout.</li>
</ul>

<h3>Was the damage cause by something or somebody outside of your flat?</h3>

<ul>
   <li>Your first point of contact should be our <a href="/index/caretaker">caretaker</a>, Gail.
   If necessary she will liaise with contractors to arrange for immediate remedial work to be
   carried out.</li>
   <li>If the situation is urgent and you cannot get in touch with Gail, you should contact...</li>
   <li>The structure of Princes Park Mansions is insured by PPM Ltd. (Extracts from that insurance
   policy can be found on this website at...). If you believe that the damage is covered by our
   buildings insurance, please contact the Board in writing with details of the damage. You can
   either post a letter in the PPM Ltd letter box located near Flat 7, or you can email
   <a class="maillink" href="mailto:insurance@princes-park-mansions.org.uk">insurance@princes-park-mansions.org.uk</a>.</li>
   <li>Sometimes more that one flat can be affected (for example, if there is a water leak).
   Please write to us even if you know, or you believe, that other residents have already contacted
   us. We must have written confirmation from each of the flats affected.</li>
   <li>We will acknowledge your letter or email within a maximum of five working days.</li>
   <li>A director will then contact our insurance broker. We will provide you with an update on
   progress within one week. Please do not contact the broker yourself, even if you have done this
   in the past. If the broker, or one of the contractors involved in any work, does contact you,
   please send a copy of this correspondence on to the Board, so we have a full record of what is
   happening.</li>
   <li>The length of time taken to assess and resolve any claim on our insurance depends on many
   factors, but we will contact you again with a full update within a maximum of three weeks.</li>
</ul>


<a href="#top" title="Return to the top of the page" class="page_nav"><i class="icon-arrow-up"></i>Back To Top</a>
<p>&nbsp;</p>
