<? $this->headTitle('Noticeboard'); ?>

<a name="top"></a><h1>Notice Board</h1>

<p>To submit messages, please contact
<a href="mailto:webmaster@princes-park-mansions.org.uk">
webmaster@princes-park-mansions.org.uk</a>.</p>

<h2>Current Messages</h2>

<table class="colouredgrid">
  <tr>
    <th>Date</th><th>Message</th>
  </tr>
  <tr class="oddrow">
    <td>8/6/2008</td><td><p>It is the intention of Board of Directors of
    Princes Park Mansions Company Ltd to enter into an agreements to carry
    out works in respect of which we are required to consult leaseholders.  
    The works to be carried out under the agreement are as follows: Repair 
    and renewal to drive and Car Park area at Princes Park Mansions, Croxteth
    Road, Liverpool, L8 3SA </p>
    <p>More information can be found in the PDF document found
    <a href="/secure/shareholders">here</a>.</p></td>
  </tr>
</table>

<h2>Archived Messages</h2>

<table class="colouredgrid">
  <tr>
    <th>Date</th><th>Message</th>
  </tr>
  <tr class="oddrow">
    <td>23/3/2007</td><td><p><b>Sale of Garage Unit 3</b></p><p>Shareholders who
    are interested in tendering for this garage unit should submit a tender with
    the following information: Name, Address, Telephone Number (optional), Email
    address (optional), Amount Offered.</p>
    <p>Conditions:</p>
    <ul>
    <li>Tender must be submitted by 5pm 30th April</li>
    <li>Tenders must be in sealed envelope with garage tender clearly marked on
    the outside</li>
    <li>Only shareholders who are currently resident at PPM and who do not
    already own a garage will be eligible to tender</li>
    <li>PPMMCL has set a reserve price of £8,500 per unit and will not accept
    tenders below this price</li>
    <li>Shareholders can inspect the independent valuation, which states that
    each garage is valued at £12,000</li>
    <li>All tenders must be submitted in writing via PPMMCL letterbox outside
    flats 7-12</li>
    <li>Late tenders will not be considered</li>
    <li>To inspect the garage please contact our caretaker Gail at flat 14A</li>
    <li>All shareholders submitting a tender must be in a position to complete
    their purchase within 40 days</li>
    </ul></td>
  </tr>
  <tr>
    <td>12/9/2006</td><td><p><b>Paper Recycling</b></p><p>Please note that bins
    for recycling paper have now been delivered. There is one bin at each end of
    the building. The blue bag pick-up service has now been stopped.
    </p></td>
  </tr>
  <tr class="oddrow">
    <td>10/1/2006</td><td><p><b>Urgent Notice</b></p><p>Following a Health and Safety
    inspection of the balcony areas by a civil engineer commissioned by PPMMCL we
    have been advised that some of the ironworks are unsafe.</p><p>Residents are
    therefore advised not to use the balconies until a full civil engineers report
    is complete and the necessary repairs can be undertaken. The required repairs
    relate to the ironworks only and not the concrete walkways. Thank you for your
    co-operation</p></td>
  </tr>
  <tr>
    <td>16/8/2006</td><td><p><b>Caretaker&#39;s Holiday</b></p><p>
    The caretaker is on holiday from 21st August to 4th September, 2006. Note
    that there will be no rubbish collection during this time.</p></td>
  </tr>
  <tr class="oddrow">
    <td>16/6/2006</td><td><p><b>Caretaker&#39;s Holiday</b></p><p>
    The caretaker is on holiday from 12th to 26th of June, 2006. Note that there
    will be no rubbish collection during this time.</p></td>
  </tr>
  <tr>
    <td>11/5/2006</td><td><p><b>Critical Notice - Water Supply</b></p><p>
    Essential work will be undertaken to the tank system in the middle block
    between the 15th and 18th of May 2006. This work is vital and unavoidable.
    </p><p>As a result there will be no hot water to affected flats for up to
    four days. In the unlikely event that the cold water supply is also
    affected, please let Gail know as soon as possible (07981-353684 or 07814-
    913545). Will will need to make alternative arrangements for affected flats.
    </p><p>We apologise in advance and assure you that the contractors will keep
    the disruption to a minimum.  Thank you for your cooperation in this matter.</p></td>
  </tr>
  <tr class="oddrow">
    <td>5/1/2006</td><td><p><b>Flat For Sale</b></p><p>1B Princes Park Mansions
    Lower ground apartment, 2 double bedrooms, drawing room with feature fireplace,
    kitchen, dining room and bathroom.</p><p>Sale price in region of 145K.
    Viewing by appointment only. Please contact Rhona Drummond on 07989-305984
    or alternatively email at <a href="mailto:rhonad@newhaven-agency.co.uk">
    rhonad@newhaven-agency.co.uk</a></p></td>
  </tr>
</table>
